# Generated by Django 5.0.1 on 2024-02-12 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('Antiques', 'Antiques'), ('Electronics', 'Electronics'), ('Paintings', 'Paintings')], default='', max_length=50)),
                ('desc', models.TextField(max_length=100)),
                ('base_price', models.FloatField()),
                ('image', models.ImageField(upload_to='pics')),
                ('time', models.TimeField()),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
