# Generated by Django 5.0.1 on 2024-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auctionapp', '0003_auction_remove_product_time_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
