# Generated by Django 5.0.1 on 2024-02-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auctionapp', '0009_alter_auction_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
