# Generated by Django 5.0.1 on 2024-02-20 00:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auctionapp', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='product',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
